// ==============================================================
// RTL generated by Vivado(TM) HLS - High-Level Synthesis from C, C++ and SystemC
// Version: 2018.3
// Copyright (C) 1986-2018 Xilinx, Inc. All Rights Reserved.
// 
// ===========================================================

#include "conv2d.h"
#include "AESL_pkg.h"

using namespace std;

namespace ap_rtl {

const sc_logic conv2d::ap_const_logic_1 = sc_dt::Log_1;
const sc_logic conv2d::ap_const_logic_0 = sc_dt::Log_0;
const sc_lv<16> conv2d::ap_ST_fsm_state1 = "1";
const sc_lv<16> conv2d::ap_ST_fsm_state2 = "10";
const sc_lv<16> conv2d::ap_ST_fsm_state3 = "100";
const sc_lv<16> conv2d::ap_ST_fsm_state4 = "1000";
const sc_lv<16> conv2d::ap_ST_fsm_state5 = "10000";
const sc_lv<16> conv2d::ap_ST_fsm_state6 = "100000";
const sc_lv<16> conv2d::ap_ST_fsm_state7 = "1000000";
const sc_lv<16> conv2d::ap_ST_fsm_state8 = "10000000";
const sc_lv<16> conv2d::ap_ST_fsm_state9 = "100000000";
const sc_lv<16> conv2d::ap_ST_fsm_state10 = "1000000000";
const sc_lv<16> conv2d::ap_ST_fsm_state11 = "10000000000";
const sc_lv<16> conv2d::ap_ST_fsm_state12 = "100000000000";
const sc_lv<16> conv2d::ap_ST_fsm_state13 = "1000000000000";
const sc_lv<16> conv2d::ap_ST_fsm_state14 = "10000000000000";
const sc_lv<16> conv2d::ap_ST_fsm_state15 = "100000000000000";
const sc_lv<16> conv2d::ap_ST_fsm_state16 = "1000000000000000";
const sc_lv<32> conv2d::ap_const_lv32_0 = "00000000000000000000000000000000";
const sc_lv<32> conv2d::ap_const_lv32_1 = "1";
const sc_lv<1> conv2d::ap_const_lv1_0 = "0";
const sc_lv<32> conv2d::ap_const_lv32_2 = "10";
const sc_lv<1> conv2d::ap_const_lv1_1 = "1";
const sc_lv<32> conv2d::ap_const_lv32_3 = "11";
const sc_lv<32> conv2d::ap_const_lv32_5 = "101";
const sc_lv<32> conv2d::ap_const_lv32_7 = "111";
const sc_lv<32> conv2d::ap_const_lv32_8 = "1000";
const sc_lv<32> conv2d::ap_const_lv32_A = "1010";
const sc_lv<32> conv2d::ap_const_lv32_B = "1011";
const sc_lv<32> conv2d::ap_const_lv32_C = "1100";
const sc_lv<32> conv2d::ap_const_lv32_D = "1101";
const sc_lv<32> conv2d::ap_const_lv32_E = "1110";
const sc_lv<32> conv2d::ap_const_lv32_F = "1111";
const sc_lv<2> conv2d::ap_const_lv2_0 = "00";
const sc_lv<2> conv2d::ap_const_lv2_1 = "1";
const sc_lv<32> conv2d::ap_const_lv32_4 = "100";
const sc_lv<3> conv2d::ap_const_lv3_0 = "000";
const sc_lv<32> conv2d::ap_const_lv32_6 = "110";
const sc_lv<32> conv2d::ap_const_lv32_9 = "1001";
const sc_lv<2> conv2d::ap_const_lv2_3 = "11";
const sc_lv<3> conv2d::ap_const_lv3_2 = "10";
const sc_lv<3> conv2d::ap_const_lv3_5 = "101";
const sc_lv<3> conv2d::ap_const_lv3_1 = "1";
const sc_lv<4> conv2d::ap_const_lv4_A = "1010";
const bool conv2d::ap_const_boolean_1 = true;

conv2d::conv2d(sc_module_name name) : sc_module(name), mVcdFile(0) {
    line_buffer_U = new conv2d_line_buffer("line_buffer_U");
    line_buffer_U->clk(ap_clk);
    line_buffer_U->reset(ap_rst);
    line_buffer_U->address0(line_buffer_address0);
    line_buffer_U->ce0(line_buffer_ce0);
    line_buffer_U->we0(line_buffer_we0);
    line_buffer_U->d0(line_buffer_d0);
    line_buffer_U->q0(line_buffer_q0);

    SC_METHOD(thread_ap_clk_no_reset_);
    dont_initialize();
    sensitive << ( ap_clk.pos() );

    SC_METHOD(thread_ap_CS_fsm_state1);
    sensitive << ( ap_CS_fsm );

    SC_METHOD(thread_ap_CS_fsm_state10);
    sensitive << ( ap_CS_fsm );

    SC_METHOD(thread_ap_CS_fsm_state11);
    sensitive << ( ap_CS_fsm );

    SC_METHOD(thread_ap_CS_fsm_state12);
    sensitive << ( ap_CS_fsm );

    SC_METHOD(thread_ap_CS_fsm_state13);
    sensitive << ( ap_CS_fsm );

    SC_METHOD(thread_ap_CS_fsm_state14);
    sensitive << ( ap_CS_fsm );

    SC_METHOD(thread_ap_CS_fsm_state15);
    sensitive << ( ap_CS_fsm );

    SC_METHOD(thread_ap_CS_fsm_state16);
    sensitive << ( ap_CS_fsm );

    SC_METHOD(thread_ap_CS_fsm_state2);
    sensitive << ( ap_CS_fsm );

    SC_METHOD(thread_ap_CS_fsm_state3);
    sensitive << ( ap_CS_fsm );

    SC_METHOD(thread_ap_CS_fsm_state4);
    sensitive << ( ap_CS_fsm );

    SC_METHOD(thread_ap_CS_fsm_state5);
    sensitive << ( ap_CS_fsm );

    SC_METHOD(thread_ap_CS_fsm_state6);
    sensitive << ( ap_CS_fsm );

    SC_METHOD(thread_ap_CS_fsm_state7);
    sensitive << ( ap_CS_fsm );

    SC_METHOD(thread_ap_CS_fsm_state8);
    sensitive << ( ap_CS_fsm );

    SC_METHOD(thread_ap_CS_fsm_state9);
    sensitive << ( ap_CS_fsm );

    SC_METHOD(thread_ap_done);
    sensitive << ( ap_CS_fsm_state2 );
    sensitive << ( exitcond8_fu_271_p2 );

    SC_METHOD(thread_ap_idle);
    sensitive << ( ap_start );
    sensitive << ( ap_CS_fsm_state1 );

    SC_METHOD(thread_ap_ready);
    sensitive << ( ap_CS_fsm_state2 );
    sensitive << ( exitcond8_fu_271_p2 );

    SC_METHOD(thread_exitcond1_fu_552_p2);
    sensitive << ( ap_CS_fsm_state12 );
    sensitive << ( i4_reg_233 );

    SC_METHOD(thread_exitcond2_fu_540_p2);
    sensitive << ( ap_CS_fsm_state11 );
    sensitive << ( y_reg_208 );

    SC_METHOD(thread_exitcond3_fu_413_p2);
    sensitive << ( tmp_reg_677 );
    sensitive << ( ap_CS_fsm_state6 );
    sensitive << ( j3_reg_174 );

    SC_METHOD(thread_exitcond4_fu_372_p2);
    sensitive << ( ap_CS_fsm_state4 );
    sensitive << ( j2_reg_163 );

    SC_METHOD(thread_exitcond5_fu_289_p2);
    sensitive << ( ap_CS_fsm_state3 );
    sensitive << ( i1_reg_151 );

    SC_METHOD(thread_exitcond6_fu_510_p2);
    sensitive << ( ap_CS_fsm_state9 );
    sensitive << ( j_reg_197 );

    SC_METHOD(thread_exitcond7_fu_476_p2);
    sensitive << ( ap_CS_fsm_state8 );
    sensitive << ( i_reg_186 );

    SC_METHOD(thread_exitcond8_fu_271_p2);
    sensitive << ( ap_CS_fsm_state2 );
    sensitive << ( x_reg_139 );

    SC_METHOD(thread_exitcond_fu_610_p2);
    sensitive << ( ap_CS_fsm_state13 );
    sensitive << ( j5_reg_256 );

    SC_METHOD(thread_i_1_fu_482_p2);
    sensitive << ( i_reg_186 );

    SC_METHOD(thread_i_2_fu_403_p2);
    sensitive << ( i1_reg_151 );

    SC_METHOD(thread_i_3_fu_558_p2);
    sensitive << ( i4_reg_233 );

    SC_METHOD(thread_input_r_address0);
    sensitive << ( ap_CS_fsm_state6 );
    sensitive << ( ap_CS_fsm_state9 );
    sensitive << ( tmp_24_cast_fu_531_p1 );
    sensitive << ( tmp_25_cast_fu_434_p1 );

    SC_METHOD(thread_input_r_ce0);
    sensitive << ( ap_CS_fsm_state6 );
    sensitive << ( ap_CS_fsm_state9 );

    SC_METHOD(thread_j5_cast_fu_606_p1);
    sensitive << ( j5_reg_256 );

    SC_METHOD(thread_j_1_fu_516_p2);
    sensitive << ( j_reg_197 );

    SC_METHOD(thread_j_2_fu_419_p2);
    sensitive << ( j3_reg_174 );

    SC_METHOD(thread_j_3_fu_378_p2);
    sensitive << ( j2_reg_163 );

    SC_METHOD(thread_j_4_fu_616_p2);
    sensitive << ( j5_reg_256 );

    SC_METHOD(thread_kernel_address0);
    sensitive << ( ap_CS_fsm_state13 );
    sensitive << ( tmp_37_cast_fu_650_p1 );

    SC_METHOD(thread_kernel_ce0);
    sensitive << ( ap_CS_fsm_state13 );

    SC_METHOD(thread_line_buffer_address0);
    sensitive << ( ap_CS_fsm_state4 );
    sensitive << ( tmp_24_cast_reg_761 );
    sensitive << ( ap_CS_fsm_state13 );
    sensitive << ( ap_CS_fsm_state5 );
    sensitive << ( ap_CS_fsm_state7 );
    sensitive << ( ap_CS_fsm_state10 );
    sensitive << ( tmp_27_cast_fu_393_p1 );
    sensitive << ( tmp_28_cast_fu_409_p1 );
    sensitive << ( tmp_26_cast_fu_471_p1 );
    sensitive << ( tmp_36_cast_fu_636_p1 );

    SC_METHOD(thread_line_buffer_ce0);
    sensitive << ( ap_CS_fsm_state4 );
    sensitive << ( ap_CS_fsm_state13 );
    sensitive << ( ap_CS_fsm_state5 );
    sensitive << ( ap_CS_fsm_state7 );
    sensitive << ( ap_CS_fsm_state10 );

    SC_METHOD(thread_line_buffer_d0);
    sensitive << ( input_r_q0 );
    sensitive << ( line_buffer_q0 );
    sensitive << ( ap_CS_fsm_state5 );
    sensitive << ( ap_CS_fsm_state7 );
    sensitive << ( ap_CS_fsm_state10 );

    SC_METHOD(thread_line_buffer_we0);
    sensitive << ( ap_CS_fsm_state5 );
    sensitive << ( ap_CS_fsm_state7 );
    sensitive << ( ap_CS_fsm_state10 );

    SC_METHOD(thread_output_r_address0);
    sensitive << ( ap_CS_fsm_state12 );
    sensitive << ( tmp_31_cast_fu_601_p1 );

    SC_METHOD(thread_output_r_ce0);
    sensitive << ( ap_CS_fsm_state12 );

    SC_METHOD(thread_output_r_d0);
    sensitive << ( ap_CS_fsm_state12 );
    sensitive << ( sum_reg_220 );

    SC_METHOD(thread_output_r_we0);
    sensitive << ( ap_CS_fsm_state12 );
    sensitive << ( exitcond1_fu_552_p2 );

    SC_METHOD(thread_p_shl2_cast_fu_335_p1);
    sensitive << ( tmp_8_fu_327_p3 );

    SC_METHOD(thread_p_shl3_cast_fu_307_p1);
    sensitive << ( tmp_6_fu_299_p3 );

    SC_METHOD(thread_p_shl4_cast_fu_362_p1);
    sensitive << ( tmp_3_fu_354_p3 );

    SC_METHOD(thread_p_shl5_cast_fu_451_p1);
    sensitive << ( tmp_17_fu_443_p3 );

    SC_METHOD(thread_p_shl7_cast_fu_576_p1);
    sensitive << ( tmp_20_fu_568_p3 );

    SC_METHOD(thread_p_shl_cast_fu_500_p1);
    sensitive << ( tmp_s_fu_492_p3 );

    SC_METHOD(thread_sum_2_fu_659_p2);
    sensitive << ( tmp_15_reg_830 );
    sensitive << ( sum_1_reg_244 );

    SC_METHOD(thread_tmp_10_cast_fu_592_p1);
    sensitive << ( y_reg_208 );

    SC_METHOD(thread_tmp_10_fu_526_p2);
    sensitive << ( tmp_1_reg_748 );
    sensitive << ( tmp_8_cast_fu_522_p1 );

    SC_METHOD(thread_tmp_11_cast_fu_564_p1);
    sensitive << ( i4_reg_233 );

    SC_METHOD(thread_tmp_11_fu_429_p2);
    sensitive << ( tmp_4_reg_694 );
    sensitive << ( tmp_cast_fu_425_p1 );

    SC_METHOD(thread_tmp_12_fu_622_p2);
    sensitive << ( y_cast_reg_771 );
    sensitive << ( j5_cast_fu_606_p1 );

    SC_METHOD(thread_tmp_13_cast_fu_627_p1);
    sensitive << ( tmp_12_fu_622_p2 );

    SC_METHOD(thread_tmp_13_fu_465_p2);
    sensitive << ( tmp_cast9_fu_461_p1 );

    SC_METHOD(thread_tmp_14_cast_fu_641_p1);
    sensitive << ( j5_reg_256 );

    SC_METHOD(thread_tmp_14_fu_388_p2);
    sensitive << ( tmp_7_reg_684 );
    sensitive << ( tmp_7_cast_fu_384_p1 );

    SC_METHOD(thread_tmp_15_fu_655_p2);
    sensitive << ( line_buffer_load_1_reg_820 );
    sensitive << ( kernel_load_reg_825 );

    SC_METHOD(thread_tmp_16_fu_398_p2);
    sensitive << ( tmp_9_reg_689 );
    sensitive << ( tmp_7_cast_fu_384_p1 );

    SC_METHOD(thread_tmp_17_fu_443_p3);
    sensitive << ( x_reg_139 );

    SC_METHOD(thread_tmp_18_fu_455_p2);
    sensitive << ( p_shl5_cast_fu_451_p1 );
    sensitive << ( tmp_9_cast_fu_439_p1 );

    SC_METHOD(thread_tmp_19_fu_596_p2);
    sensitive << ( tmp_18_reg_735 );
    sensitive << ( tmp_10_cast_fu_592_p1 );

    SC_METHOD(thread_tmp_1_cast_fu_488_p1);
    sensitive << ( i_reg_186 );

    SC_METHOD(thread_tmp_1_fu_504_p2);
    sensitive << ( tmp_1_cast_fu_488_p1 );
    sensitive << ( p_shl_cast_fu_500_p1 );

    SC_METHOD(thread_tmp_20_fu_568_p3);
    sensitive << ( i4_reg_233 );

    SC_METHOD(thread_tmp_21_fu_580_p2);
    sensitive << ( p_shl7_cast_fu_576_p1 );
    sensitive << ( tmp_11_cast_fu_564_p1 );

    SC_METHOD(thread_tmp_22_fu_586_p2);
    sensitive << ( p_shl7_cast_fu_576_p1 );
    sensitive << ( tmp_11_cast_fu_564_p1 );

    SC_METHOD(thread_tmp_23_fu_631_p2);
    sensitive << ( tmp_22_reg_797 );
    sensitive << ( tmp_13_cast_fu_627_p1 );

    SC_METHOD(thread_tmp_24_cast_fu_531_p1);
    sensitive << ( tmp_10_fu_526_p2 );

    SC_METHOD(thread_tmp_24_fu_645_p2);
    sensitive << ( tmp_21_reg_792 );
    sensitive << ( tmp_14_cast_fu_641_p1 );

    SC_METHOD(thread_tmp_25_cast_fu_434_p1);
    sensitive << ( tmp_11_fu_429_p2 );

    SC_METHOD(thread_tmp_26_cast_fu_471_p1);
    sensitive << ( tmp_13_fu_465_p2 );

    SC_METHOD(thread_tmp_27_cast_fu_393_p1);
    sensitive << ( tmp_14_fu_388_p2 );

    SC_METHOD(thread_tmp_28_cast_fu_409_p1);
    sensitive << ( tmp_16_reg_712 );

    SC_METHOD(thread_tmp_2_fu_345_p2);
    sensitive << ( x_cast_reg_664 );

    SC_METHOD(thread_tmp_31_cast_fu_601_p1);
    sensitive << ( tmp_19_fu_596_p2 );

    SC_METHOD(thread_tmp_36_cast_fu_636_p1);
    sensitive << ( tmp_23_fu_631_p2 );

    SC_METHOD(thread_tmp_37_cast_fu_650_p1);
    sensitive << ( tmp_24_fu_645_p2 );

    SC_METHOD(thread_tmp_3_cast_fu_350_p1);
    sensitive << ( tmp_2_fu_345_p2 );

    SC_METHOD(thread_tmp_3_fu_354_p3);
    sensitive << ( tmp_2_fu_345_p2 );

    SC_METHOD(thread_tmp_4_cast_fu_295_p1);
    sensitive << ( i1_reg_151 );

    SC_METHOD(thread_tmp_4_fu_366_p2);
    sensitive << ( tmp_3_cast_fu_350_p1 );
    sensitive << ( p_shl4_cast_fu_362_p1 );

    SC_METHOD(thread_tmp_5_fu_317_p2);
    sensitive << ( i1_reg_151 );

    SC_METHOD(thread_tmp_6_cast_fu_323_p1);
    sensitive << ( tmp_5_fu_317_p2 );

    SC_METHOD(thread_tmp_6_fu_299_p3);
    sensitive << ( i1_reg_151 );

    SC_METHOD(thread_tmp_7_cast_fu_384_p1);
    sensitive << ( j2_reg_163 );

    SC_METHOD(thread_tmp_7_fu_311_p2);
    sensitive << ( tmp_4_cast_fu_295_p1 );
    sensitive << ( p_shl3_cast_fu_307_p1 );

    SC_METHOD(thread_tmp_8_cast_fu_522_p1);
    sensitive << ( j_reg_197 );

    SC_METHOD(thread_tmp_8_fu_327_p3);
    sensitive << ( tmp_5_fu_317_p2 );

    SC_METHOD(thread_tmp_9_cast_fu_439_p1);
    sensitive << ( x_reg_139 );

    SC_METHOD(thread_tmp_9_fu_339_p2);
    sensitive << ( tmp_6_cast_fu_323_p1 );
    sensitive << ( p_shl2_cast_fu_335_p1 );

    SC_METHOD(thread_tmp_cast9_fu_461_p1);
    sensitive << ( j3_reg_174 );

    SC_METHOD(thread_tmp_cast_fu_425_p1);
    sensitive << ( j3_reg_174 );

    SC_METHOD(thread_tmp_fu_283_p2);
    sensitive << ( ap_CS_fsm_state2 );
    sensitive << ( exitcond8_fu_271_p2 );
    sensitive << ( x_reg_139 );

    SC_METHOD(thread_tmp_s_fu_492_p3);
    sensitive << ( i_reg_186 );

    SC_METHOD(thread_x_1_fu_277_p2);
    sensitive << ( x_reg_139 );

    SC_METHOD(thread_x_cast_fu_267_p1);
    sensitive << ( x_reg_139 );

    SC_METHOD(thread_y_1_fu_546_p2);
    sensitive << ( y_reg_208 );

    SC_METHOD(thread_y_cast_fu_536_p1);
    sensitive << ( y_reg_208 );

    SC_METHOD(thread_ap_NS_fsm);
    sensitive << ( ap_start );
    sensitive << ( ap_CS_fsm );
    sensitive << ( ap_CS_fsm_state1 );
    sensitive << ( ap_CS_fsm_state2 );
    sensitive << ( tmp_fu_283_p2 );
    sensitive << ( tmp_reg_677 );
    sensitive << ( exitcond8_fu_271_p2 );
    sensitive << ( ap_CS_fsm_state3 );
    sensitive << ( exitcond5_fu_289_p2 );
    sensitive << ( ap_CS_fsm_state4 );
    sensitive << ( exitcond4_fu_372_p2 );
    sensitive << ( ap_CS_fsm_state6 );
    sensitive << ( exitcond3_fu_413_p2 );
    sensitive << ( ap_CS_fsm_state8 );
    sensitive << ( exitcond7_fu_476_p2 );
    sensitive << ( ap_CS_fsm_state9 );
    sensitive << ( exitcond6_fu_510_p2 );
    sensitive << ( ap_CS_fsm_state11 );
    sensitive << ( ap_CS_fsm_state12 );
    sensitive << ( exitcond1_fu_552_p2 );
    sensitive << ( ap_CS_fsm_state13 );
    sensitive << ( exitcond_fu_610_p2 );
    sensitive << ( exitcond2_fu_540_p2 );

    SC_THREAD(thread_hdltv_gen);
    sensitive << ( ap_clk.pos() );

    ap_CS_fsm = "0000000000000001";
    static int apTFileNum = 0;
    stringstream apTFilenSS;
    apTFilenSS << "conv2d_sc_trace_" << apTFileNum ++;
    string apTFn = apTFilenSS.str();
    mVcdFile = sc_create_vcd_trace_file(apTFn.c_str());
    mVcdFile->set_time_unit(1, SC_PS);
    if (1) {
#ifdef __HLS_TRACE_LEVEL_PORT__
    sc_trace(mVcdFile, ap_clk, "(port)ap_clk");
    sc_trace(mVcdFile, ap_rst, "(port)ap_rst");
    sc_trace(mVcdFile, ap_start, "(port)ap_start");
    sc_trace(mVcdFile, ap_done, "(port)ap_done");
    sc_trace(mVcdFile, ap_idle, "(port)ap_idle");
    sc_trace(mVcdFile, ap_ready, "(port)ap_ready");
    sc_trace(mVcdFile, input_r_address0, "(port)input_r_address0");
    sc_trace(mVcdFile, input_r_ce0, "(port)input_r_ce0");
    sc_trace(mVcdFile, input_r_q0, "(port)input_r_q0");
    sc_trace(mVcdFile, kernel_address0, "(port)kernel_address0");
    sc_trace(mVcdFile, kernel_ce0, "(port)kernel_ce0");
    sc_trace(mVcdFile, kernel_q0, "(port)kernel_q0");
    sc_trace(mVcdFile, output_r_address0, "(port)output_r_address0");
    sc_trace(mVcdFile, output_r_ce0, "(port)output_r_ce0");
    sc_trace(mVcdFile, output_r_we0, "(port)output_r_we0");
    sc_trace(mVcdFile, output_r_d0, "(port)output_r_d0");
#endif
#ifdef __HLS_TRACE_LEVEL_INT__
    sc_trace(mVcdFile, ap_CS_fsm, "ap_CS_fsm");
    sc_trace(mVcdFile, ap_CS_fsm_state1, "ap_CS_fsm_state1");
    sc_trace(mVcdFile, x_cast_fu_267_p1, "x_cast_fu_267_p1");
    sc_trace(mVcdFile, x_cast_reg_664, "x_cast_reg_664");
    sc_trace(mVcdFile, ap_CS_fsm_state2, "ap_CS_fsm_state2");
    sc_trace(mVcdFile, x_1_fu_277_p2, "x_1_fu_277_p2");
    sc_trace(mVcdFile, x_1_reg_672, "x_1_reg_672");
    sc_trace(mVcdFile, tmp_fu_283_p2, "tmp_fu_283_p2");
    sc_trace(mVcdFile, tmp_reg_677, "tmp_reg_677");
    sc_trace(mVcdFile, exitcond8_fu_271_p2, "exitcond8_fu_271_p2");
    sc_trace(mVcdFile, tmp_7_fu_311_p2, "tmp_7_fu_311_p2");
    sc_trace(mVcdFile, tmp_7_reg_684, "tmp_7_reg_684");
    sc_trace(mVcdFile, ap_CS_fsm_state3, "ap_CS_fsm_state3");
    sc_trace(mVcdFile, exitcond5_fu_289_p2, "exitcond5_fu_289_p2");
    sc_trace(mVcdFile, tmp_9_fu_339_p2, "tmp_9_fu_339_p2");
    sc_trace(mVcdFile, tmp_9_reg_689, "tmp_9_reg_689");
    sc_trace(mVcdFile, tmp_4_fu_366_p2, "tmp_4_fu_366_p2");
    sc_trace(mVcdFile, tmp_4_reg_694, "tmp_4_reg_694");
    sc_trace(mVcdFile, j_3_fu_378_p2, "j_3_fu_378_p2");
    sc_trace(mVcdFile, j_3_reg_702, "j_3_reg_702");
    sc_trace(mVcdFile, ap_CS_fsm_state4, "ap_CS_fsm_state4");
    sc_trace(mVcdFile, exitcond4_fu_372_p2, "exitcond4_fu_372_p2");
    sc_trace(mVcdFile, tmp_16_fu_398_p2, "tmp_16_fu_398_p2");
    sc_trace(mVcdFile, tmp_16_reg_712, "tmp_16_reg_712");
    sc_trace(mVcdFile, i_2_fu_403_p2, "i_2_fu_403_p2");
    sc_trace(mVcdFile, j_2_fu_419_p2, "j_2_fu_419_p2");
    sc_trace(mVcdFile, j_2_reg_725, "j_2_reg_725");
    sc_trace(mVcdFile, ap_CS_fsm_state6, "ap_CS_fsm_state6");
    sc_trace(mVcdFile, exitcond3_fu_413_p2, "exitcond3_fu_413_p2");
    sc_trace(mVcdFile, tmp_18_fu_455_p2, "tmp_18_fu_455_p2");
    sc_trace(mVcdFile, tmp_18_reg_735, "tmp_18_reg_735");
    sc_trace(mVcdFile, i_1_fu_482_p2, "i_1_fu_482_p2");
    sc_trace(mVcdFile, i_1_reg_743, "i_1_reg_743");
    sc_trace(mVcdFile, ap_CS_fsm_state8, "ap_CS_fsm_state8");
    sc_trace(mVcdFile, tmp_1_fu_504_p2, "tmp_1_fu_504_p2");
    sc_trace(mVcdFile, tmp_1_reg_748, "tmp_1_reg_748");
    sc_trace(mVcdFile, exitcond7_fu_476_p2, "exitcond7_fu_476_p2");
    sc_trace(mVcdFile, j_1_fu_516_p2, "j_1_fu_516_p2");
    sc_trace(mVcdFile, j_1_reg_756, "j_1_reg_756");
    sc_trace(mVcdFile, ap_CS_fsm_state9, "ap_CS_fsm_state9");
    sc_trace(mVcdFile, tmp_24_cast_fu_531_p1, "tmp_24_cast_fu_531_p1");
    sc_trace(mVcdFile, tmp_24_cast_reg_761, "tmp_24_cast_reg_761");
    sc_trace(mVcdFile, exitcond6_fu_510_p2, "exitcond6_fu_510_p2");
    sc_trace(mVcdFile, y_cast_fu_536_p1, "y_cast_fu_536_p1");
    sc_trace(mVcdFile, y_cast_reg_771, "y_cast_reg_771");
    sc_trace(mVcdFile, ap_CS_fsm_state11, "ap_CS_fsm_state11");
    sc_trace(mVcdFile, y_1_fu_546_p2, "y_1_fu_546_p2");
    sc_trace(mVcdFile, y_1_reg_779, "y_1_reg_779");
    sc_trace(mVcdFile, i_3_fu_558_p2, "i_3_fu_558_p2");
    sc_trace(mVcdFile, i_3_reg_787, "i_3_reg_787");
    sc_trace(mVcdFile, ap_CS_fsm_state12, "ap_CS_fsm_state12");
    sc_trace(mVcdFile, tmp_21_fu_580_p2, "tmp_21_fu_580_p2");
    sc_trace(mVcdFile, tmp_21_reg_792, "tmp_21_reg_792");
    sc_trace(mVcdFile, exitcond1_fu_552_p2, "exitcond1_fu_552_p2");
    sc_trace(mVcdFile, tmp_22_fu_586_p2, "tmp_22_fu_586_p2");
    sc_trace(mVcdFile, tmp_22_reg_797, "tmp_22_reg_797");
    sc_trace(mVcdFile, j_4_fu_616_p2, "j_4_fu_616_p2");
    sc_trace(mVcdFile, j_4_reg_805, "j_4_reg_805");
    sc_trace(mVcdFile, ap_CS_fsm_state13, "ap_CS_fsm_state13");
    sc_trace(mVcdFile, exitcond_fu_610_p2, "exitcond_fu_610_p2");
    sc_trace(mVcdFile, line_buffer_q0, "line_buffer_q0");
    sc_trace(mVcdFile, line_buffer_load_1_reg_820, "line_buffer_load_1_reg_820");
    sc_trace(mVcdFile, ap_CS_fsm_state14, "ap_CS_fsm_state14");
    sc_trace(mVcdFile, kernel_load_reg_825, "kernel_load_reg_825");
    sc_trace(mVcdFile, tmp_15_fu_655_p2, "tmp_15_fu_655_p2");
    sc_trace(mVcdFile, tmp_15_reg_830, "tmp_15_reg_830");
    sc_trace(mVcdFile, ap_CS_fsm_state15, "ap_CS_fsm_state15");
    sc_trace(mVcdFile, sum_2_fu_659_p2, "sum_2_fu_659_p2");
    sc_trace(mVcdFile, ap_CS_fsm_state16, "ap_CS_fsm_state16");
    sc_trace(mVcdFile, line_buffer_address0, "line_buffer_address0");
    sc_trace(mVcdFile, line_buffer_ce0, "line_buffer_ce0");
    sc_trace(mVcdFile, line_buffer_we0, "line_buffer_we0");
    sc_trace(mVcdFile, line_buffer_d0, "line_buffer_d0");
    sc_trace(mVcdFile, x_reg_139, "x_reg_139");
    sc_trace(mVcdFile, exitcond2_fu_540_p2, "exitcond2_fu_540_p2");
    sc_trace(mVcdFile, i1_reg_151, "i1_reg_151");
    sc_trace(mVcdFile, j2_reg_163, "j2_reg_163");
    sc_trace(mVcdFile, ap_CS_fsm_state5, "ap_CS_fsm_state5");
    sc_trace(mVcdFile, j3_reg_174, "j3_reg_174");
    sc_trace(mVcdFile, ap_CS_fsm_state7, "ap_CS_fsm_state7");
    sc_trace(mVcdFile, i_reg_186, "i_reg_186");
    sc_trace(mVcdFile, j_reg_197, "j_reg_197");
    sc_trace(mVcdFile, ap_CS_fsm_state10, "ap_CS_fsm_state10");
    sc_trace(mVcdFile, y_reg_208, "y_reg_208");
    sc_trace(mVcdFile, sum_reg_220, "sum_reg_220");
    sc_trace(mVcdFile, i4_reg_233, "i4_reg_233");
    sc_trace(mVcdFile, sum_1_reg_244, "sum_1_reg_244");
    sc_trace(mVcdFile, j5_reg_256, "j5_reg_256");
    sc_trace(mVcdFile, tmp_27_cast_fu_393_p1, "tmp_27_cast_fu_393_p1");
    sc_trace(mVcdFile, tmp_28_cast_fu_409_p1, "tmp_28_cast_fu_409_p1");
    sc_trace(mVcdFile, tmp_25_cast_fu_434_p1, "tmp_25_cast_fu_434_p1");
    sc_trace(mVcdFile, tmp_26_cast_fu_471_p1, "tmp_26_cast_fu_471_p1");
    sc_trace(mVcdFile, tmp_31_cast_fu_601_p1, "tmp_31_cast_fu_601_p1");
    sc_trace(mVcdFile, tmp_36_cast_fu_636_p1, "tmp_36_cast_fu_636_p1");
    sc_trace(mVcdFile, tmp_37_cast_fu_650_p1, "tmp_37_cast_fu_650_p1");
    sc_trace(mVcdFile, tmp_6_fu_299_p3, "tmp_6_fu_299_p3");
    sc_trace(mVcdFile, tmp_4_cast_fu_295_p1, "tmp_4_cast_fu_295_p1");
    sc_trace(mVcdFile, p_shl3_cast_fu_307_p1, "p_shl3_cast_fu_307_p1");
    sc_trace(mVcdFile, tmp_5_fu_317_p2, "tmp_5_fu_317_p2");
    sc_trace(mVcdFile, tmp_8_fu_327_p3, "tmp_8_fu_327_p3");
    sc_trace(mVcdFile, tmp_6_cast_fu_323_p1, "tmp_6_cast_fu_323_p1");
    sc_trace(mVcdFile, p_shl2_cast_fu_335_p1, "p_shl2_cast_fu_335_p1");
    sc_trace(mVcdFile, tmp_2_fu_345_p2, "tmp_2_fu_345_p2");
    sc_trace(mVcdFile, tmp_3_fu_354_p3, "tmp_3_fu_354_p3");
    sc_trace(mVcdFile, tmp_3_cast_fu_350_p1, "tmp_3_cast_fu_350_p1");
    sc_trace(mVcdFile, p_shl4_cast_fu_362_p1, "p_shl4_cast_fu_362_p1");
    sc_trace(mVcdFile, tmp_7_cast_fu_384_p1, "tmp_7_cast_fu_384_p1");
    sc_trace(mVcdFile, tmp_14_fu_388_p2, "tmp_14_fu_388_p2");
    sc_trace(mVcdFile, tmp_cast_fu_425_p1, "tmp_cast_fu_425_p1");
    sc_trace(mVcdFile, tmp_11_fu_429_p2, "tmp_11_fu_429_p2");
    sc_trace(mVcdFile, tmp_17_fu_443_p3, "tmp_17_fu_443_p3");
    sc_trace(mVcdFile, p_shl5_cast_fu_451_p1, "p_shl5_cast_fu_451_p1");
    sc_trace(mVcdFile, tmp_9_cast_fu_439_p1, "tmp_9_cast_fu_439_p1");
    sc_trace(mVcdFile, tmp_cast9_fu_461_p1, "tmp_cast9_fu_461_p1");
    sc_trace(mVcdFile, tmp_13_fu_465_p2, "tmp_13_fu_465_p2");
    sc_trace(mVcdFile, tmp_s_fu_492_p3, "tmp_s_fu_492_p3");
    sc_trace(mVcdFile, tmp_1_cast_fu_488_p1, "tmp_1_cast_fu_488_p1");
    sc_trace(mVcdFile, p_shl_cast_fu_500_p1, "p_shl_cast_fu_500_p1");
    sc_trace(mVcdFile, tmp_8_cast_fu_522_p1, "tmp_8_cast_fu_522_p1");
    sc_trace(mVcdFile, tmp_10_fu_526_p2, "tmp_10_fu_526_p2");
    sc_trace(mVcdFile, tmp_20_fu_568_p3, "tmp_20_fu_568_p3");
    sc_trace(mVcdFile, p_shl7_cast_fu_576_p1, "p_shl7_cast_fu_576_p1");
    sc_trace(mVcdFile, tmp_11_cast_fu_564_p1, "tmp_11_cast_fu_564_p1");
    sc_trace(mVcdFile, tmp_10_cast_fu_592_p1, "tmp_10_cast_fu_592_p1");
    sc_trace(mVcdFile, tmp_19_fu_596_p2, "tmp_19_fu_596_p2");
    sc_trace(mVcdFile, j5_cast_fu_606_p1, "j5_cast_fu_606_p1");
    sc_trace(mVcdFile, tmp_12_fu_622_p2, "tmp_12_fu_622_p2");
    sc_trace(mVcdFile, tmp_13_cast_fu_627_p1, "tmp_13_cast_fu_627_p1");
    sc_trace(mVcdFile, tmp_23_fu_631_p2, "tmp_23_fu_631_p2");
    sc_trace(mVcdFile, tmp_14_cast_fu_641_p1, "tmp_14_cast_fu_641_p1");
    sc_trace(mVcdFile, tmp_24_fu_645_p2, "tmp_24_fu_645_p2");
    sc_trace(mVcdFile, ap_NS_fsm, "ap_NS_fsm");
#endif

    }
    mHdltvinHandle.open("conv2d.hdltvin.dat");
    mHdltvoutHandle.open("conv2d.hdltvout.dat");
}

conv2d::~conv2d() {
    if (mVcdFile) 
        sc_close_vcd_trace_file(mVcdFile);

    mHdltvinHandle << "] " << endl;
    mHdltvoutHandle << "] " << endl;
    mHdltvinHandle.close();
    mHdltvoutHandle.close();
    delete line_buffer_U;
}

void conv2d::thread_ap_clk_no_reset_() {
    if ( ap_rst.read() == ap_const_logic_1) {
        ap_CS_fsm = ap_ST_fsm_state1;
    } else {
        ap_CS_fsm = ap_NS_fsm.read();
    }
    if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state2.read()) && 
         esl_seteq<1,1,1>(exitcond8_fu_271_p2.read(), ap_const_lv1_0) && 
         esl_seteq<1,1,1>(tmp_fu_283_p2.read(), ap_const_lv1_0))) {
        i1_reg_151 = ap_const_lv2_1;
    } else if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state4.read()) && 
                esl_seteq<1,1,1>(ap_const_lv1_1, exitcond4_fu_372_p2.read()))) {
        i1_reg_151 = i_2_fu_403_p2.read();
    }
    if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state11.read()) && 
         esl_seteq<1,1,1>(ap_const_lv1_0, exitcond2_fu_540_p2.read()))) {
        i4_reg_233 = ap_const_lv2_0;
    } else if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state13.read()) && 
                esl_seteq<1,1,1>(ap_const_lv1_1, exitcond_fu_610_p2.read()))) {
        i4_reg_233 = i_3_reg_787.read();
    }
    if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state2.read()) && 
         esl_seteq<1,1,1>(exitcond8_fu_271_p2.read(), ap_const_lv1_0) && 
         esl_seteq<1,1,1>(tmp_fu_283_p2.read(), ap_const_lv1_1))) {
        i_reg_186 = ap_const_lv2_0;
    } else if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state9.read()) && 
                esl_seteq<1,1,1>(ap_const_lv1_1, exitcond6_fu_510_p2.read()))) {
        i_reg_186 = i_1_reg_743.read();
    }
    if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state3.read()) && 
         esl_seteq<1,1,1>(ap_const_lv1_0, exitcond5_fu_289_p2.read()))) {
        j2_reg_163 = ap_const_lv3_0;
    } else if (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state5.read())) {
        j2_reg_163 = j_3_reg_702.read();
    }
    if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state3.read()) && 
         esl_seteq<1,1,1>(exitcond5_fu_289_p2.read(), ap_const_lv1_1))) {
        j3_reg_174 = ap_const_lv3_0;
    } else if (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state7.read())) {
        j3_reg_174 = j_2_reg_725.read();
    }
    if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state12.read()) && 
         esl_seteq<1,1,1>(ap_const_lv1_0, exitcond1_fu_552_p2.read()))) {
        j5_reg_256 = ap_const_lv2_0;
    } else if (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state16.read())) {
        j5_reg_256 = j_4_reg_805.read();
    }
    if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state8.read()) && 
         esl_seteq<1,1,1>(ap_const_lv1_0, exitcond7_fu_476_p2.read()))) {
        j_reg_197 = ap_const_lv3_0;
    } else if (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state10.read())) {
        j_reg_197 = j_1_reg_756.read();
    }
    if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state12.read()) && 
         esl_seteq<1,1,1>(ap_const_lv1_0, exitcond1_fu_552_p2.read()))) {
        sum_1_reg_244 = sum_reg_220.read();
    } else if (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state16.read())) {
        sum_1_reg_244 = sum_2_fu_659_p2.read();
    }
    if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state11.read()) && 
         esl_seteq<1,1,1>(ap_const_lv1_0, exitcond2_fu_540_p2.read()))) {
        sum_reg_220 = ap_const_lv32_0;
    } else if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state13.read()) && 
                esl_seteq<1,1,1>(ap_const_lv1_1, exitcond_fu_610_p2.read()))) {
        sum_reg_220 = sum_1_reg_244.read();
    }
    if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state11.read()) && 
         esl_seteq<1,1,1>(ap_const_lv1_1, exitcond2_fu_540_p2.read()))) {
        x_reg_139 = x_1_reg_672.read();
    } else if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state1.read()) && 
                esl_seteq<1,1,1>(ap_start.read(), ap_const_logic_1))) {
        x_reg_139 = ap_const_lv2_0;
    }
    if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state12.read()) && 
         esl_seteq<1,1,1>(ap_const_lv1_1, exitcond1_fu_552_p2.read()))) {
        y_reg_208 = y_1_reg_779.read();
    } else if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state6.read()) && 
                (esl_seteq<1,1,1>(ap_const_lv1_1, exitcond3_fu_413_p2.read()) || 
                 esl_seteq<1,1,1>(tmp_reg_677.read(), ap_const_lv1_1)))) {
        y_reg_208 = ap_const_lv2_0;
    }
    if (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state8.read())) {
        i_1_reg_743 = i_1_fu_482_p2.read();
    }
    if (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state12.read())) {
        i_3_reg_787 = i_3_fu_558_p2.read();
    }
    if (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state9.read())) {
        j_1_reg_756 = j_1_fu_516_p2.read();
    }
    if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state6.read()) && esl_seteq<1,1,1>(tmp_reg_677.read(), ap_const_lv1_0))) {
        j_2_reg_725 = j_2_fu_419_p2.read();
    }
    if (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state4.read())) {
        j_3_reg_702 = j_3_fu_378_p2.read();
    }
    if (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state13.read())) {
        j_4_reg_805 = j_4_fu_616_p2.read();
    }
    if (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state14.read())) {
        kernel_load_reg_825 = kernel_q0.read();
        line_buffer_load_1_reg_820 = line_buffer_q0.read();
    }
    if (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state15.read())) {
        tmp_15_reg_830 = tmp_15_fu_655_p2.read();
    }
    if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state4.read()) && esl_seteq<1,1,1>(ap_const_lv1_0, exitcond4_fu_372_p2.read()))) {
        tmp_16_reg_712 = tmp_16_fu_398_p2.read();
    }
    if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state6.read()) && (esl_seteq<1,1,1>(ap_const_lv1_1, exitcond3_fu_413_p2.read()) || 
  esl_seteq<1,1,1>(tmp_reg_677.read(), ap_const_lv1_1)))) {
        tmp_18_reg_735 = tmp_18_fu_455_p2.read();
    }
    if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state8.read()) && esl_seteq<1,1,1>(ap_const_lv1_0, exitcond7_fu_476_p2.read()))) {
        tmp_1_reg_748 = tmp_1_fu_504_p2.read();
    }
    if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state12.read()) && esl_seteq<1,1,1>(ap_const_lv1_0, exitcond1_fu_552_p2.read()))) {
        tmp_21_reg_792 = tmp_21_fu_580_p2.read();
        tmp_22_reg_797 = tmp_22_fu_586_p2.read();
    }
    if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state9.read()) && esl_seteq<1,1,1>(ap_const_lv1_0, exitcond6_fu_510_p2.read()))) {
        tmp_24_cast_reg_761 = tmp_24_cast_fu_531_p1.read();
    }
    if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state3.read()) && esl_seteq<1,1,1>(exitcond5_fu_289_p2.read(), ap_const_lv1_1))) {
        tmp_4_reg_694 = tmp_4_fu_366_p2.read();
    }
    if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state3.read()) && esl_seteq<1,1,1>(ap_const_lv1_0, exitcond5_fu_289_p2.read()))) {
        tmp_7_reg_684 = tmp_7_fu_311_p2.read();
        tmp_9_reg_689 = tmp_9_fu_339_p2.read();
    }
    if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state2.read()) && esl_seteq<1,1,1>(exitcond8_fu_271_p2.read(), ap_const_lv1_0))) {
        tmp_reg_677 = tmp_fu_283_p2.read();
    }
    if (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state2.read())) {
        x_1_reg_672 = x_1_fu_277_p2.read();
        x_cast_reg_664 = x_cast_fu_267_p1.read();
    }
    if (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state11.read())) {
        y_1_reg_779 = y_1_fu_546_p2.read();
        y_cast_reg_771 = y_cast_fu_536_p1.read();
    }
}

void conv2d::thread_ap_CS_fsm_state1() {
    ap_CS_fsm_state1 = ap_CS_fsm.read()[0];
}

void conv2d::thread_ap_CS_fsm_state10() {
    ap_CS_fsm_state10 = ap_CS_fsm.read()[9];
}

void conv2d::thread_ap_CS_fsm_state11() {
    ap_CS_fsm_state11 = ap_CS_fsm.read()[10];
}

void conv2d::thread_ap_CS_fsm_state12() {
    ap_CS_fsm_state12 = ap_CS_fsm.read()[11];
}

void conv2d::thread_ap_CS_fsm_state13() {
    ap_CS_fsm_state13 = ap_CS_fsm.read()[12];
}

void conv2d::thread_ap_CS_fsm_state14() {
    ap_CS_fsm_state14 = ap_CS_fsm.read()[13];
}

void conv2d::thread_ap_CS_fsm_state15() {
    ap_CS_fsm_state15 = ap_CS_fsm.read()[14];
}

void conv2d::thread_ap_CS_fsm_state16() {
    ap_CS_fsm_state16 = ap_CS_fsm.read()[15];
}

void conv2d::thread_ap_CS_fsm_state2() {
    ap_CS_fsm_state2 = ap_CS_fsm.read()[1];
}

void conv2d::thread_ap_CS_fsm_state3() {
    ap_CS_fsm_state3 = ap_CS_fsm.read()[2];
}

void conv2d::thread_ap_CS_fsm_state4() {
    ap_CS_fsm_state4 = ap_CS_fsm.read()[3];
}

void conv2d::thread_ap_CS_fsm_state5() {
    ap_CS_fsm_state5 = ap_CS_fsm.read()[4];
}

void conv2d::thread_ap_CS_fsm_state6() {
    ap_CS_fsm_state6 = ap_CS_fsm.read()[5];
}

void conv2d::thread_ap_CS_fsm_state7() {
    ap_CS_fsm_state7 = ap_CS_fsm.read()[6];
}

void conv2d::thread_ap_CS_fsm_state8() {
    ap_CS_fsm_state8 = ap_CS_fsm.read()[7];
}

void conv2d::thread_ap_CS_fsm_state9() {
    ap_CS_fsm_state9 = ap_CS_fsm.read()[8];
}

void conv2d::thread_ap_done() {
    if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state2.read()) && 
         esl_seteq<1,1,1>(exitcond8_fu_271_p2.read(), ap_const_lv1_1))) {
        ap_done = ap_const_logic_1;
    } else {
        ap_done = ap_const_logic_0;
    }
}

void conv2d::thread_ap_idle() {
    if ((esl_seteq<1,1,1>(ap_const_logic_0, ap_start.read()) && 
         esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state1.read()))) {
        ap_idle = ap_const_logic_1;
    } else {
        ap_idle = ap_const_logic_0;
    }
}

void conv2d::thread_ap_ready() {
    if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state2.read()) && 
         esl_seteq<1,1,1>(exitcond8_fu_271_p2.read(), ap_const_lv1_1))) {
        ap_ready = ap_const_logic_1;
    } else {
        ap_ready = ap_const_logic_0;
    }
}

void conv2d::thread_exitcond1_fu_552_p2() {
    exitcond1_fu_552_p2 = (!i4_reg_233.read().is_01() || !ap_const_lv2_3.is_01())? sc_lv<1>(): sc_lv<1>(i4_reg_233.read() == ap_const_lv2_3);
}

void conv2d::thread_exitcond2_fu_540_p2() {
    exitcond2_fu_540_p2 = (!y_reg_208.read().is_01() || !ap_const_lv2_3.is_01())? sc_lv<1>(): sc_lv<1>(y_reg_208.read() == ap_const_lv2_3);
}

void conv2d::thread_exitcond3_fu_413_p2() {
    exitcond3_fu_413_p2 = (!j3_reg_174.read().is_01() || !ap_const_lv3_5.is_01())? sc_lv<1>(): sc_lv<1>(j3_reg_174.read() == ap_const_lv3_5);
}

void conv2d::thread_exitcond4_fu_372_p2() {
    exitcond4_fu_372_p2 = (!j2_reg_163.read().is_01() || !ap_const_lv3_5.is_01())? sc_lv<1>(): sc_lv<1>(j2_reg_163.read() == ap_const_lv3_5);
}

void conv2d::thread_exitcond5_fu_289_p2() {
    exitcond5_fu_289_p2 = (!i1_reg_151.read().is_01() || !ap_const_lv2_3.is_01())? sc_lv<1>(): sc_lv<1>(i1_reg_151.read() == ap_const_lv2_3);
}

void conv2d::thread_exitcond6_fu_510_p2() {
    exitcond6_fu_510_p2 = (!j_reg_197.read().is_01() || !ap_const_lv3_5.is_01())? sc_lv<1>(): sc_lv<1>(j_reg_197.read() == ap_const_lv3_5);
}

void conv2d::thread_exitcond7_fu_476_p2() {
    exitcond7_fu_476_p2 = (!i_reg_186.read().is_01() || !ap_const_lv2_3.is_01())? sc_lv<1>(): sc_lv<1>(i_reg_186.read() == ap_const_lv2_3);
}

void conv2d::thread_exitcond8_fu_271_p2() {
    exitcond8_fu_271_p2 = (!x_reg_139.read().is_01() || !ap_const_lv2_3.is_01())? sc_lv<1>(): sc_lv<1>(x_reg_139.read() == ap_const_lv2_3);
}

void conv2d::thread_exitcond_fu_610_p2() {
    exitcond_fu_610_p2 = (!j5_reg_256.read().is_01() || !ap_const_lv2_3.is_01())? sc_lv<1>(): sc_lv<1>(j5_reg_256.read() == ap_const_lv2_3);
}

void conv2d::thread_i_1_fu_482_p2() {
    i_1_fu_482_p2 = (!i_reg_186.read().is_01() || !ap_const_lv2_1.is_01())? sc_lv<2>(): (sc_biguint<2>(i_reg_186.read()) + sc_biguint<2>(ap_const_lv2_1));
}

void conv2d::thread_i_2_fu_403_p2() {
    i_2_fu_403_p2 = (!i1_reg_151.read().is_01() || !ap_const_lv2_1.is_01())? sc_lv<2>(): (sc_biguint<2>(i1_reg_151.read()) + sc_biguint<2>(ap_const_lv2_1));
}

void conv2d::thread_i_3_fu_558_p2() {
    i_3_fu_558_p2 = (!i4_reg_233.read().is_01() || !ap_const_lv2_1.is_01())? sc_lv<2>(): (sc_biguint<2>(i4_reg_233.read()) + sc_biguint<2>(ap_const_lv2_1));
}

void conv2d::thread_input_r_address0() {
    if (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state9.read())) {
        input_r_address0 =  (sc_lv<5>) (tmp_24_cast_fu_531_p1.read());
    } else if (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state6.read())) {
        input_r_address0 =  (sc_lv<5>) (tmp_25_cast_fu_434_p1.read());
    } else {
        input_r_address0 = "XXXXX";
    }
}

void conv2d::thread_input_r_ce0() {
    if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state6.read()) || 
         esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state9.read()))) {
        input_r_ce0 = ap_const_logic_1;
    } else {
        input_r_ce0 = ap_const_logic_0;
    }
}

void conv2d::thread_j5_cast_fu_606_p1() {
    j5_cast_fu_606_p1 = esl_zext<3,2>(j5_reg_256.read());
}

void conv2d::thread_j_1_fu_516_p2() {
    j_1_fu_516_p2 = (!j_reg_197.read().is_01() || !ap_const_lv3_1.is_01())? sc_lv<3>(): (sc_biguint<3>(j_reg_197.read()) + sc_biguint<3>(ap_const_lv3_1));
}

void conv2d::thread_j_2_fu_419_p2() {
    j_2_fu_419_p2 = (!j3_reg_174.read().is_01() || !ap_const_lv3_1.is_01())? sc_lv<3>(): (sc_biguint<3>(j3_reg_174.read()) + sc_biguint<3>(ap_const_lv3_1));
}

void conv2d::thread_j_3_fu_378_p2() {
    j_3_fu_378_p2 = (!j2_reg_163.read().is_01() || !ap_const_lv3_1.is_01())? sc_lv<3>(): (sc_biguint<3>(j2_reg_163.read()) + sc_biguint<3>(ap_const_lv3_1));
}

void conv2d::thread_j_4_fu_616_p2() {
    j_4_fu_616_p2 = (!j5_reg_256.read().is_01() || !ap_const_lv2_1.is_01())? sc_lv<2>(): (sc_biguint<2>(j5_reg_256.read()) + sc_biguint<2>(ap_const_lv2_1));
}

void conv2d::thread_kernel_address0() {
    kernel_address0 =  (sc_lv<4>) (tmp_37_cast_fu_650_p1.read());
}

void conv2d::thread_kernel_ce0() {
    if (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state13.read())) {
        kernel_ce0 = ap_const_logic_1;
    } else {
        kernel_ce0 = ap_const_logic_0;
    }
}

void conv2d::thread_line_buffer_address0() {
    if (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state13.read())) {
        line_buffer_address0 =  (sc_lv<4>) (tmp_36_cast_fu_636_p1.read());
    } else if (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state10.read())) {
        line_buffer_address0 =  (sc_lv<4>) (tmp_24_cast_reg_761.read());
    } else if (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state7.read())) {
        line_buffer_address0 =  (sc_lv<4>) (tmp_26_cast_fu_471_p1.read());
    } else if (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state5.read())) {
        line_buffer_address0 =  (sc_lv<4>) (tmp_28_cast_fu_409_p1.read());
    } else if (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state4.read())) {
        line_buffer_address0 =  (sc_lv<4>) (tmp_27_cast_fu_393_p1.read());
    } else {
        line_buffer_address0 =  (sc_lv<4>) ("XXXX");
    }
}

void conv2d::thread_line_buffer_ce0() {
    if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state4.read()) || 
         esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state13.read()) || 
         esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state5.read()) || 
         esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state7.read()) || 
         esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state10.read()))) {
        line_buffer_ce0 = ap_const_logic_1;
    } else {
        line_buffer_ce0 = ap_const_logic_0;
    }
}

void conv2d::thread_line_buffer_d0() {
    if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state7.read()) || 
         esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state10.read()))) {
        line_buffer_d0 = input_r_q0.read();
    } else if (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state5.read())) {
        line_buffer_d0 = line_buffer_q0.read();
    } else {
        line_buffer_d0 =  (sc_lv<32>) ("XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX");
    }
}

void conv2d::thread_line_buffer_we0() {
    if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state5.read()) || 
         esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state7.read()) || 
         esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state10.read()))) {
        line_buffer_we0 = ap_const_logic_1;
    } else {
        line_buffer_we0 = ap_const_logic_0;
    }
}

void conv2d::thread_output_r_address0() {
    output_r_address0 =  (sc_lv<4>) (tmp_31_cast_fu_601_p1.read());
}

void conv2d::thread_output_r_ce0() {
    if (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state12.read())) {
        output_r_ce0 = ap_const_logic_1;
    } else {
        output_r_ce0 = ap_const_logic_0;
    }
}

void conv2d::thread_output_r_d0() {
    output_r_d0 = sum_reg_220.read();
}

void conv2d::thread_output_r_we0() {
    if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state12.read()) && 
         esl_seteq<1,1,1>(ap_const_lv1_1, exitcond1_fu_552_p2.read()))) {
        output_r_we0 = ap_const_logic_1;
    } else {
        output_r_we0 = ap_const_logic_0;
    }
}

void conv2d::thread_p_shl2_cast_fu_335_p1() {
    p_shl2_cast_fu_335_p1 = esl_zext<5,4>(tmp_8_fu_327_p3.read());
}

void conv2d::thread_p_shl3_cast_fu_307_p1() {
    p_shl3_cast_fu_307_p1 = esl_zext<5,4>(tmp_6_fu_299_p3.read());
}

void conv2d::thread_p_shl4_cast_fu_362_p1() {
    p_shl4_cast_fu_362_p1 = esl_zext<6,5>(tmp_3_fu_354_p3.read());
}

void conv2d::thread_p_shl5_cast_fu_451_p1() {
    p_shl5_cast_fu_451_p1 = esl_zext<5,4>(tmp_17_fu_443_p3.read());
}

void conv2d::thread_p_shl7_cast_fu_576_p1() {
    p_shl7_cast_fu_576_p1 = esl_zext<5,4>(tmp_20_fu_568_p3.read());
}

void conv2d::thread_p_shl_cast_fu_500_p1() {
    p_shl_cast_fu_500_p1 = esl_zext<5,4>(tmp_s_fu_492_p3.read());
}

void conv2d::thread_sum_2_fu_659_p2() {
    sum_2_fu_659_p2 = (!sum_1_reg_244.read().is_01() || !tmp_15_reg_830.read().is_01())? sc_lv<32>(): (sc_biguint<32>(sum_1_reg_244.read()) + sc_biguint<32>(tmp_15_reg_830.read()));
}

void conv2d::thread_tmp_10_cast_fu_592_p1() {
    tmp_10_cast_fu_592_p1 = esl_zext<5,2>(y_reg_208.read());
}

void conv2d::thread_tmp_10_fu_526_p2() {
    tmp_10_fu_526_p2 = (!tmp_1_reg_748.read().is_01() || !tmp_8_cast_fu_522_p1.read().is_01())? sc_lv<5>(): (sc_biguint<5>(tmp_1_reg_748.read()) + sc_biguint<5>(tmp_8_cast_fu_522_p1.read()));
}

void conv2d::thread_tmp_11_cast_fu_564_p1() {
    tmp_11_cast_fu_564_p1 = esl_zext<5,2>(i4_reg_233.read());
}

void conv2d::thread_tmp_11_fu_429_p2() {
    tmp_11_fu_429_p2 = (!tmp_4_reg_694.read().is_01() || !tmp_cast_fu_425_p1.read().is_01())? sc_lv<6>(): (sc_biguint<6>(tmp_4_reg_694.read()) + sc_biguint<6>(tmp_cast_fu_425_p1.read()));
}

void conv2d::thread_tmp_12_fu_622_p2() {
    tmp_12_fu_622_p2 = (!j5_cast_fu_606_p1.read().is_01() || !y_cast_reg_771.read().is_01())? sc_lv<3>(): (sc_biguint<3>(j5_cast_fu_606_p1.read()) + sc_biguint<3>(y_cast_reg_771.read()));
}

void conv2d::thread_tmp_13_cast_fu_627_p1() {
    tmp_13_cast_fu_627_p1 = esl_zext<5,3>(tmp_12_fu_622_p2.read());
}

void conv2d::thread_tmp_13_fu_465_p2() {
    tmp_13_fu_465_p2 = (!tmp_cast9_fu_461_p1.read().is_01() || !ap_const_lv4_A.is_01())? sc_lv<4>(): (sc_biguint<4>(tmp_cast9_fu_461_p1.read()) + sc_bigint<4>(ap_const_lv4_A));
}

void conv2d::thread_tmp_14_cast_fu_641_p1() {
    tmp_14_cast_fu_641_p1 = esl_zext<5,2>(j5_reg_256.read());
}

void conv2d::thread_tmp_14_fu_388_p2() {
    tmp_14_fu_388_p2 = (!tmp_7_reg_684.read().is_01() || !tmp_7_cast_fu_384_p1.read().is_01())? sc_lv<5>(): (sc_biguint<5>(tmp_7_reg_684.read()) + sc_biguint<5>(tmp_7_cast_fu_384_p1.read()));
}

void conv2d::thread_tmp_15_fu_655_p2() {
    tmp_15_fu_655_p2 = (!kernel_load_reg_825.read().is_01() || !line_buffer_load_1_reg_820.read().is_01())? sc_lv<32>(): sc_bigint<32>(kernel_load_reg_825.read()) * sc_bigint<32>(line_buffer_load_1_reg_820.read());
}

void conv2d::thread_tmp_16_fu_398_p2() {
    tmp_16_fu_398_p2 = (!tmp_9_reg_689.read().is_01() || !tmp_7_cast_fu_384_p1.read().is_01())? sc_lv<5>(): (sc_biguint<5>(tmp_9_reg_689.read()) + sc_biguint<5>(tmp_7_cast_fu_384_p1.read()));
}

void conv2d::thread_tmp_17_fu_443_p3() {
    tmp_17_fu_443_p3 = esl_concat<2,2>(x_reg_139.read(), ap_const_lv2_0);
}

void conv2d::thread_tmp_18_fu_455_p2() {
    tmp_18_fu_455_p2 = (!p_shl5_cast_fu_451_p1.read().is_01() || !tmp_9_cast_fu_439_p1.read().is_01())? sc_lv<5>(): (sc_biguint<5>(p_shl5_cast_fu_451_p1.read()) - sc_biguint<5>(tmp_9_cast_fu_439_p1.read()));
}

void conv2d::thread_tmp_19_fu_596_p2() {
    tmp_19_fu_596_p2 = (!tmp_18_reg_735.read().is_01() || !tmp_10_cast_fu_592_p1.read().is_01())? sc_lv<5>(): (sc_biguint<5>(tmp_18_reg_735.read()) + sc_biguint<5>(tmp_10_cast_fu_592_p1.read()));
}

void conv2d::thread_tmp_1_cast_fu_488_p1() {
    tmp_1_cast_fu_488_p1 = esl_zext<5,2>(i_reg_186.read());
}

void conv2d::thread_tmp_1_fu_504_p2() {
    tmp_1_fu_504_p2 = (!tmp_1_cast_fu_488_p1.read().is_01() || !p_shl_cast_fu_500_p1.read().is_01())? sc_lv<5>(): (sc_biguint<5>(tmp_1_cast_fu_488_p1.read()) + sc_biguint<5>(p_shl_cast_fu_500_p1.read()));
}

void conv2d::thread_tmp_20_fu_568_p3() {
    tmp_20_fu_568_p3 = esl_concat<2,2>(i4_reg_233.read(), ap_const_lv2_0);
}

void conv2d::thread_tmp_21_fu_580_p2() {
    tmp_21_fu_580_p2 = (!p_shl7_cast_fu_576_p1.read().is_01() || !tmp_11_cast_fu_564_p1.read().is_01())? sc_lv<5>(): (sc_biguint<5>(p_shl7_cast_fu_576_p1.read()) - sc_biguint<5>(tmp_11_cast_fu_564_p1.read()));
}

void conv2d::thread_tmp_22_fu_586_p2() {
    tmp_22_fu_586_p2 = (!tmp_11_cast_fu_564_p1.read().is_01() || !p_shl7_cast_fu_576_p1.read().is_01())? sc_lv<5>(): (sc_biguint<5>(tmp_11_cast_fu_564_p1.read()) + sc_biguint<5>(p_shl7_cast_fu_576_p1.read()));
}

void conv2d::thread_tmp_23_fu_631_p2() {
    tmp_23_fu_631_p2 = (!tmp_22_reg_797.read().is_01() || !tmp_13_cast_fu_627_p1.read().is_01())? sc_lv<5>(): (sc_biguint<5>(tmp_22_reg_797.read()) + sc_biguint<5>(tmp_13_cast_fu_627_p1.read()));
}

void conv2d::thread_tmp_24_cast_fu_531_p1() {
    tmp_24_cast_fu_531_p1 = esl_zext<64,5>(tmp_10_fu_526_p2.read());
}

void conv2d::thread_tmp_24_fu_645_p2() {
    tmp_24_fu_645_p2 = (!tmp_21_reg_792.read().is_01() || !tmp_14_cast_fu_641_p1.read().is_01())? sc_lv<5>(): (sc_biguint<5>(tmp_21_reg_792.read()) + sc_biguint<5>(tmp_14_cast_fu_641_p1.read()));
}

void conv2d::thread_tmp_25_cast_fu_434_p1() {
    tmp_25_cast_fu_434_p1 = esl_zext<64,6>(tmp_11_fu_429_p2.read());
}

void conv2d::thread_tmp_26_cast_fu_471_p1() {
    tmp_26_cast_fu_471_p1 = esl_zext<64,4>(tmp_13_fu_465_p2.read());
}

void conv2d::thread_tmp_27_cast_fu_393_p1() {
    tmp_27_cast_fu_393_p1 = esl_zext<64,5>(tmp_14_fu_388_p2.read());
}

void conv2d::thread_tmp_28_cast_fu_409_p1() {
    tmp_28_cast_fu_409_p1 = esl_zext<64,5>(tmp_16_reg_712.read());
}

void conv2d::thread_tmp_2_fu_345_p2() {
    tmp_2_fu_345_p2 = (!x_cast_reg_664.read().is_01() || !ap_const_lv3_2.is_01())? sc_lv<3>(): (sc_biguint<3>(x_cast_reg_664.read()) + sc_biguint<3>(ap_const_lv3_2));
}

void conv2d::thread_tmp_31_cast_fu_601_p1() {
    tmp_31_cast_fu_601_p1 = esl_sext<64,5>(tmp_19_fu_596_p2.read());
}

void conv2d::thread_tmp_36_cast_fu_636_p1() {
    tmp_36_cast_fu_636_p1 = esl_zext<64,5>(tmp_23_fu_631_p2.read());
}

void conv2d::thread_tmp_37_cast_fu_650_p1() {
    tmp_37_cast_fu_650_p1 = esl_sext<64,5>(tmp_24_fu_645_p2.read());
}

void conv2d::thread_tmp_3_cast_fu_350_p1() {
    tmp_3_cast_fu_350_p1 = esl_zext<6,3>(tmp_2_fu_345_p2.read());
}

void conv2d::thread_tmp_3_fu_354_p3() {
    tmp_3_fu_354_p3 = esl_concat<3,2>(tmp_2_fu_345_p2.read(), ap_const_lv2_0);
}

void conv2d::thread_tmp_4_cast_fu_295_p1() {
    tmp_4_cast_fu_295_p1 = esl_zext<5,2>(i1_reg_151.read());
}

void conv2d::thread_tmp_4_fu_366_p2() {
    tmp_4_fu_366_p2 = (!tmp_3_cast_fu_350_p1.read().is_01() || !p_shl4_cast_fu_362_p1.read().is_01())? sc_lv<6>(): (sc_biguint<6>(tmp_3_cast_fu_350_p1.read()) + sc_biguint<6>(p_shl4_cast_fu_362_p1.read()));
}

void conv2d::thread_tmp_5_fu_317_p2() {
    tmp_5_fu_317_p2 = (!i1_reg_151.read().is_01() || !ap_const_lv2_3.is_01())? sc_lv<2>(): (sc_biguint<2>(i1_reg_151.read()) + sc_bigint<2>(ap_const_lv2_3));
}

void conv2d::thread_tmp_6_cast_fu_323_p1() {
    tmp_6_cast_fu_323_p1 = esl_zext<5,2>(tmp_5_fu_317_p2.read());
}

void conv2d::thread_tmp_6_fu_299_p3() {
    tmp_6_fu_299_p3 = esl_concat<2,2>(i1_reg_151.read(), ap_const_lv2_0);
}

void conv2d::thread_tmp_7_cast_fu_384_p1() {
    tmp_7_cast_fu_384_p1 = esl_zext<5,3>(j2_reg_163.read());
}

void conv2d::thread_tmp_7_fu_311_p2() {
    tmp_7_fu_311_p2 = (!tmp_4_cast_fu_295_p1.read().is_01() || !p_shl3_cast_fu_307_p1.read().is_01())? sc_lv<5>(): (sc_biguint<5>(tmp_4_cast_fu_295_p1.read()) + sc_biguint<5>(p_shl3_cast_fu_307_p1.read()));
}

void conv2d::thread_tmp_8_cast_fu_522_p1() {
    tmp_8_cast_fu_522_p1 = esl_zext<5,3>(j_reg_197.read());
}

void conv2d::thread_tmp_8_fu_327_p3() {
    tmp_8_fu_327_p3 = esl_concat<2,2>(tmp_5_fu_317_p2.read(), ap_const_lv2_0);
}

void conv2d::thread_tmp_9_cast_fu_439_p1() {
    tmp_9_cast_fu_439_p1 = esl_zext<5,2>(x_reg_139.read());
}

void conv2d::thread_tmp_9_fu_339_p2() {
    tmp_9_fu_339_p2 = (!tmp_6_cast_fu_323_p1.read().is_01() || !p_shl2_cast_fu_335_p1.read().is_01())? sc_lv<5>(): (sc_biguint<5>(tmp_6_cast_fu_323_p1.read()) + sc_biguint<5>(p_shl2_cast_fu_335_p1.read()));
}

void conv2d::thread_tmp_cast9_fu_461_p1() {
    tmp_cast9_fu_461_p1 = esl_zext<4,3>(j3_reg_174.read());
}

void conv2d::thread_tmp_cast_fu_425_p1() {
    tmp_cast_fu_425_p1 = esl_zext<6,3>(j3_reg_174.read());
}

void conv2d::thread_tmp_fu_283_p2() {
    tmp_fu_283_p2 = (!x_reg_139.read().is_01() || !ap_const_lv2_0.is_01())? sc_lv<1>(): sc_lv<1>(x_reg_139.read() == ap_const_lv2_0);
}

void conv2d::thread_tmp_s_fu_492_p3() {
    tmp_s_fu_492_p3 = esl_concat<2,2>(i_reg_186.read(), ap_const_lv2_0);
}

void conv2d::thread_x_1_fu_277_p2() {
    x_1_fu_277_p2 = (!x_reg_139.read().is_01() || !ap_const_lv2_1.is_01())? sc_lv<2>(): (sc_biguint<2>(x_reg_139.read()) + sc_biguint<2>(ap_const_lv2_1));
}

void conv2d::thread_x_cast_fu_267_p1() {
    x_cast_fu_267_p1 = esl_zext<3,2>(x_reg_139.read());
}

void conv2d::thread_y_1_fu_546_p2() {
    y_1_fu_546_p2 = (!y_reg_208.read().is_01() || !ap_const_lv2_1.is_01())? sc_lv<2>(): (sc_biguint<2>(y_reg_208.read()) + sc_biguint<2>(ap_const_lv2_1));
}

void conv2d::thread_y_cast_fu_536_p1() {
    y_cast_fu_536_p1 = esl_zext<3,2>(y_reg_208.read());
}

void conv2d::thread_ap_NS_fsm() {
    switch (ap_CS_fsm.read().to_uint64()) {
        case 1 : 
            if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state1.read()) && esl_seteq<1,1,1>(ap_start.read(), ap_const_logic_1))) {
                ap_NS_fsm = ap_ST_fsm_state2;
            } else {
                ap_NS_fsm = ap_ST_fsm_state1;
            }
            break;
        case 2 : 
            if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state2.read()) && esl_seteq<1,1,1>(exitcond8_fu_271_p2.read(), ap_const_lv1_1))) {
                ap_NS_fsm = ap_ST_fsm_state1;
            } else if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state2.read()) && esl_seteq<1,1,1>(exitcond8_fu_271_p2.read(), ap_const_lv1_0) && esl_seteq<1,1,1>(tmp_fu_283_p2.read(), ap_const_lv1_1))) {
                ap_NS_fsm = ap_ST_fsm_state8;
            } else {
                ap_NS_fsm = ap_ST_fsm_state3;
            }
            break;
        case 4 : 
            if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state3.read()) && esl_seteq<1,1,1>(exitcond5_fu_289_p2.read(), ap_const_lv1_1))) {
                ap_NS_fsm = ap_ST_fsm_state6;
            } else {
                ap_NS_fsm = ap_ST_fsm_state4;
            }
            break;
        case 8 : 
            if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state4.read()) && esl_seteq<1,1,1>(ap_const_lv1_1, exitcond4_fu_372_p2.read()))) {
                ap_NS_fsm = ap_ST_fsm_state3;
            } else {
                ap_NS_fsm = ap_ST_fsm_state5;
            }
            break;
        case 16 : 
            ap_NS_fsm = ap_ST_fsm_state4;
            break;
        case 32 : 
            if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state6.read()) && (esl_seteq<1,1,1>(ap_const_lv1_1, exitcond3_fu_413_p2.read()) || 
  esl_seteq<1,1,1>(tmp_reg_677.read(), ap_const_lv1_1)))) {
                ap_NS_fsm = ap_ST_fsm_state11;
            } else {
                ap_NS_fsm = ap_ST_fsm_state7;
            }
            break;
        case 64 : 
            ap_NS_fsm = ap_ST_fsm_state6;
            break;
        case 128 : 
            if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state8.read()) && esl_seteq<1,1,1>(ap_const_lv1_1, exitcond7_fu_476_p2.read()))) {
                ap_NS_fsm = ap_ST_fsm_state6;
            } else {
                ap_NS_fsm = ap_ST_fsm_state9;
            }
            break;
        case 256 : 
            if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state9.read()) && esl_seteq<1,1,1>(ap_const_lv1_1, exitcond6_fu_510_p2.read()))) {
                ap_NS_fsm = ap_ST_fsm_state8;
            } else {
                ap_NS_fsm = ap_ST_fsm_state10;
            }
            break;
        case 512 : 
            ap_NS_fsm = ap_ST_fsm_state9;
            break;
        case 1024 : 
            if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state11.read()) && esl_seteq<1,1,1>(ap_const_lv1_1, exitcond2_fu_540_p2.read()))) {
                ap_NS_fsm = ap_ST_fsm_state2;
            } else {
                ap_NS_fsm = ap_ST_fsm_state12;
            }
            break;
        case 2048 : 
            if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state12.read()) && esl_seteq<1,1,1>(ap_const_lv1_1, exitcond1_fu_552_p2.read()))) {
                ap_NS_fsm = ap_ST_fsm_state11;
            } else {
                ap_NS_fsm = ap_ST_fsm_state13;
            }
            break;
        case 4096 : 
            if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state13.read()) && esl_seteq<1,1,1>(ap_const_lv1_1, exitcond_fu_610_p2.read()))) {
                ap_NS_fsm = ap_ST_fsm_state12;
            } else {
                ap_NS_fsm = ap_ST_fsm_state14;
            }
            break;
        case 8192 : 
            ap_NS_fsm = ap_ST_fsm_state15;
            break;
        case 16384 : 
            ap_NS_fsm = ap_ST_fsm_state16;
            break;
        case 32768 : 
            ap_NS_fsm = ap_ST_fsm_state13;
            break;
        default : 
            ap_NS_fsm =  (sc_lv<16>) ("XXXXXXXXXXXXXXXX");
            break;
    }
}

void conv2d::thread_hdltv_gen() {
    const char* dump_tv = std::getenv("AP_WRITE_TV");
    if (!(dump_tv && string(dump_tv) == "on")) return;

    wait();

    mHdltvinHandle << "[ " << endl;
    mHdltvoutHandle << "[ " << endl;
    int ap_cycleNo = 0;
    while (1) {
        wait();
        const char* mComma = ap_cycleNo == 0 ? " " : ", " ;
        mHdltvinHandle << mComma << "{"  <<  " \"ap_rst\" :  \"" << ap_rst.read() << "\" ";
        mHdltvinHandle << " , " <<  " \"ap_start\" :  \"" << ap_start.read() << "\" ";
        mHdltvoutHandle << mComma << "{"  <<  " \"ap_done\" :  \"" << ap_done.read() << "\" ";
        mHdltvoutHandle << " , " <<  " \"ap_idle\" :  \"" << ap_idle.read() << "\" ";
        mHdltvoutHandle << " , " <<  " \"ap_ready\" :  \"" << ap_ready.read() << "\" ";
        mHdltvoutHandle << " , " <<  " \"input_r_address0\" :  \"" << input_r_address0.read() << "\" ";
        mHdltvoutHandle << " , " <<  " \"input_r_ce0\" :  \"" << input_r_ce0.read() << "\" ";
        mHdltvinHandle << " , " <<  " \"input_r_q0\" :  \"" << input_r_q0.read() << "\" ";
        mHdltvoutHandle << " , " <<  " \"kernel_address0\" :  \"" << kernel_address0.read() << "\" ";
        mHdltvoutHandle << " , " <<  " \"kernel_ce0\" :  \"" << kernel_ce0.read() << "\" ";
        mHdltvinHandle << " , " <<  " \"kernel_q0\" :  \"" << kernel_q0.read() << "\" ";
        mHdltvoutHandle << " , " <<  " \"output_r_address0\" :  \"" << output_r_address0.read() << "\" ";
        mHdltvoutHandle << " , " <<  " \"output_r_ce0\" :  \"" << output_r_ce0.read() << "\" ";
        mHdltvoutHandle << " , " <<  " \"output_r_we0\" :  \"" << output_r_we0.read() << "\" ";
        mHdltvoutHandle << " , " <<  " \"output_r_d0\" :  \"" << output_r_d0.read() << "\" ";
        mHdltvinHandle << "}" << std::endl;
        mHdltvoutHandle << "}" << std::endl;
        ap_cycleNo++;
    }
}

}

